# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: North Is ⇡ The enemy's gate is down
email: adam@northisup.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://northisup.com" # the base hostname & protocol for your site
twitter_username: northisup
github_username:  northisup
permalink: '/blog/:title/'

# Build settings
markdown: kramdown
exclude:
  - vendor

sass:
  sass_dir: _sass

embedly:
  api_key: 0f1e60a8ba5f11e0a4f24040d3dc5c07

disqus:
  shortname: northisup

gems:
  - jekyll-embedly-plugin
  # - jekyll-mentions
  # - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
