# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb', 'serials.md', 'serials']
markdown: rdiscount
permalink: /blog/:title/
# configuration required for some pages

domain: northisup.com
title: N⇡
author: adam
email: adam@northisup.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-4048470-1

github:
  username: northisup

disqus:
  id: northisup

embedly:
  api_key: 0f1e60a8ba5f11e0a4f24040d3dc5c07

  soundcloud:
    color: 0066FF # SoundCloud specific parameter for colorful players
    width: 500px

  vimeo:
    width: 500px
